(() => {
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const W=canvas.width,H=canvas.height, launcher={x:W/2,y:74}, R=12, GRAVITY=.155;
  const $=s=>document.querySelector(s), mapsEl=$('#mapSelect');
  const maps=[
    ['Orbit Orchard','A friendly constellation garden', [[.19,.28],[.33,.22],[.5,.31],[.67,.22],[.81,.28],[.26,.43],[.43,.47],[.57,.47],[.74,.43],[.18,.62],[.36,.64],[.5,.57],[.64,.64],[.82,.62]]],
    ['Moonlace','A drifting lunar braid', [[.23,.25],[.39,.29],[.56,.25],[.72,.3],[.3,.42],[.47,.48],[.64,.43],[.2,.59],[.4,.63],[.6,.62],[.8,.58]]],
    ['Astral Steps','A staircase through starlight', [[.2,.23],[.34,.3],[.48,.37],[.62,.44],[.76,.51],[.2,.53],[.34,.6],[.48,.67],[.62,.6],[.76,.67]]],
    ['Comet Choir','Two bright travelling arcs', [[.18,.33],[.28,.26],[.4,.22],[.52,.23],[.64,.28],[.76,.36],[.24,.57],[.37,.5],[.5,.48],[.63,.5],[.76,.57]]],
    ['Velvet Vortex','A spiral around a sleeping star', [[.5,.22],[.63,.26],[.72,.38],[.69,.53],[.56,.62],[.4,.59],[.3,.48],[.32,.33],[.44,.3],[.55,.38],[.55,.49],[.46,.5]]],
    ['Twin Tides','Two mirrored cosmic waves', [[.18,.26],[.3,.36],[.42,.42],[.5,.33],[.58,.42],[.7,.36],[.82,.26],[.18,.62],[.3,.53],[.42,.57],[.5,.67],[.58,.57],[.7,.53],[.82,.62]]],
    ['Nebula Needle','A precise central gauntlet', [[.5,.2],[.42,.29],[.58,.29],[.5,.38],[.35,.43],[.65,.43],[.43,.51],[.57,.51],[.5,.6],[.34,.65],[.66,.65]]],
    ['Aurora Bridge','A shimmering high road', [[.15,.36],[.27,.29],[.39,.35],[.5,.26],[.61,.35],[.73,.29],[.85,.36],[.23,.55],[.37,.6],[.5,.53],[.63,.6],[.77,.55]]],
    ['Starfall Cathedral','A grand constellation window', [[.5,.18],[.35,.29],[.65,.29],[.26,.43],[.5,.39],[.74,.43],[.2,.59],[.38,.58],[.62,.58],[.8,.59],[.5,.69]]],
    ['Eclipse Engine','A finale of rotating rings', [[.5,.22],[.64,.28],[.72,.42],[.64,.56],[.5,.62],[.36,.56],[.28,.42],[.36,.28],[.5,.38],[.58,.42],[.5,.49],[.42,.42]]]
  ];
  let map=0, pegs=[], ball=null, aim=null, active=0, scores=[0,0], shots=[5,5], running=false, sound=true, warpCooldown=0;
  const audio=()=>{if(!sound)return; try { const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=230+Math.random()*300;g.gain.setValueAtTime(.045,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.07);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.08) }catch{}};
  function loadMap(n){map=n; pegs=maps[n][2].map((p,i)=>({x:p[0]*W,y:p[1]*H+45,hit:false,type:i%7===0?'gold':i%11===0?'warp':'normal',phase:Math.random()*6})); ball=null; aim=null; active=0;scores=[0,0];shots=[5,5];warpCooldown=0;renderMaps();updateUI();}
  function renderMaps(){mapsEl.innerHTML='';maps.forEach((m,i)=>{let b=document.createElement('button');b.textContent=i+1;b.title=m[0];b.className=i===map?'selected':'';b.onclick=()=>{loadMap(i);running=true;$('#startOverlay').classList.add('hidden')};mapsEl.append(b)});$('#mapName').textContent=maps[map][0]}
  function updateUI(){for(let i=0;i<2;i++){ $(`#p${i+1}Score`).textContent=String(scores[i]).padStart(6,'0');$(`#p${i+1}Balls`).textContent=String(shots[i]).padStart(2,'0');$(`#p${i+1}Meter`).style.width=`${Math.min(100,scores[i]/90)}%`; $(`#player${i?'Two':'One'}Card`).classList.toggle('active',i===active)}$('#turnText').textContent=shots[active]>0?`PLAYER ${active+1}'S TURN`:'FINAL ORBIT'}
  function shoot(x,y){if(ball||!running||shots[active]<=0)return;let dx=x-launcher.x,dy=y-launcher.y,d=Math.hypot(dx,dy); if(d<20)return;let power=Math.min(14,Math.max(7,d*.055));ball={x:launcher.x,y:launcher.y,vx:dx/d*power,vy:dy/d*power,r:10,trail:[],earned:0};aim=null;audio()}
  function hitPeg(p){if(p.hit)return;p.hit=true;let pts=p.type==='gold'?20:p.type==='warp'?15:10;ball.earned+=pts;scores[active]+=pts;if(p.type==='warp'&&warpCooldown<=0){warpCooldown=20;let target=pegs.find(q=>!q.hit&&q!==p);if(target){ball.x=target.x;ball.y=target.y;ball.vx*=-.55;ball.vy=-4;}}audio();updateUI()}
  function endShot(){if(!ball)return;shots[active]--; if(pegs.every(p=>p.hit)){scores[active]+=100;shots[active]=0;} ball=null;warpCooldown=0;if(shots[0]<=0&&shots[1]<=0){running=false;setTimeout(showResult,350)}else{active=active?0:1;updateUI()}}
  function showResult(){let t=scores[0]===scores[1]?'A STELLAR DRAW':`PLAYER ${scores[0]>scores[1]?1:2} WINS`;$('#resultTitle').textContent=t;$('#resultDetail').textContent=scores[0]===scores[1]?`${scores[0]} points each — the cosmos calls it even.`:`${Math.max(...scores).toLocaleString()} points illuminate the night.`;$('#resultOverlay').classList.remove('hidden')}
  function physics(){if(!ball)return;ball.trail.unshift({x:ball.x,y:ball.y});ball.trail.length=12;ball.vy+=GRAVITY;ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.998;if(ball.x<ball.r||ball.x>W-ball.r){ball.vx*=-.8;ball.x=Math.max(ball.r,Math.min(W-ball.r,ball.x));audio()}if(ball.y<ball.r){ball.vy*=-.8;ball.y=ball.r}for(const p of pegs){let dx=ball.x-p.x,dy=ball.y-p.y,d=Math.hypot(dx,dy),min=ball.r+R;if(!p.hit&&d<min){let nx=dx/d,ny=dy/d,dot=ball.vx*nx+ball.vy*ny;ball.vx-=2*dot*nx;ball.vy-=2*dot*ny;ball.x=p.x+nx*min;ball.y=p.y+ny*min;hitPeg(p)}}if(warpCooldown>0)warpCooldown--;if(ball.y>H+30)endShot()}
  function glow(x,y,r,c){let g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill()}
  function draw(){ctx.clearRect(0,0,W,H);let bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#17104a');bg.addColorStop(.55,'#0d0b2e');bg.addColorStop(1,'#07071b');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(let i=0;i<65;i++){let x=(i*89+23)%W,y=(i*i*17+70)%H;ctx.fillStyle=`rgba(255,255,255,${.12+(i%4)*.04})`;ctx.fillRect(x,y,1,1)}glow(W*.5,H*.48,250,'rgba(88,73,204,.12)');
    // launcher
    ctx.save();ctx.translate(launcher.x,launcher.y);ctx.fillStyle='#f6eeff';ctx.shadowBlur=22;ctx.shadowColor='#bda5ff';ctx.beginPath();ctx.arc(0,0,15,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#2d1e5d';ctx.beginPath();ctx.arc(0,0,6,0,7);ctx.fill();ctx.restore();
    if(aim&&!ball){ctx.strokeStyle='rgba(255,255,255,.58)';ctx.setLineDash([5,8]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(launcher.x,launcher.y);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([])}
    for(const p of pegs){if(p.hit)continue;let c=p.type==='gold'?'#ffd35a':p.type==='warp'?'#cf8bff':'#55ebff';glow(p.x,p.y,R*2.9,c+'55');ctx.fillStyle=c;ctx.beginPath();ctx.arc(p.x,p.y,R,0,7);ctx.fill();ctx.fillStyle='rgba(255,255,255,.6)';ctx.beginPath();ctx.arc(p.x-3,p.y-4,3,0,7);ctx.fill();if(p.type==='gold'){ctx.fillStyle='#fff3b2';ctx.font='16px Outfit';ctx.fillText('✦',p.x-7,p.y+6)}}
    // score bowls
    ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(32,H-16);ctx.quadraticCurveTo(W*.25,H-95,W*.5,H-35);ctx.quadraticCurveTo(W*.75,H-95,W-32,H-16);ctx.stroke();
    if(ball){ball.trail.forEach((q,i)=>{ctx.fillStyle=`rgba(255,255,255,${.25-i*.018})`;ctx.beginPath();ctx.arc(q.x,q.y,ball.r*(1-i/20),0,7);ctx.fill()});glow(ball.x,ball.y,36,active?'rgba(255,120,155,.7)':'rgba(85,235,255,.7)');ctx.fillStyle=active?'#ff789b':'#55ebff';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,7);ctx.fill()} ctx.fillStyle='rgba(255,255,255,.45)';ctx.font='500 11px DM Mono';ctx.textAlign='center';ctx.fillText('LAUNCH STAR',launcher.x,32);ctx.textAlign='left';}
  function loop(){physics();draw();requestAnimationFrame(loop)}
  function pointer(e){let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*W/r.width,y:(p.clientY-r.top)*H/r.height}}canvas.addEventListener('pointerdown',e=>{if(!running||ball)return;aim=pointer(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(aim)aim=pointer(e)});canvas.addEventListener('pointerup',e=>shoot(pointer(e).x,pointer(e).y));
  $('#startButton').onclick=()=>{running=true;$('#startOverlay').classList.add('hidden')};$('#rematchButton').onclick=()=>{loadMap(map);running=true;$('#resultOverlay').classList.add('hidden')};$('#mapsButton').onclick=()=>{$('#resultOverlay').classList.add('hidden');$('#startOverlay').classList.remove('hidden')};$('#newGameButton').onclick=()=>{loadMap(map);running=true;$('#resultOverlay').classList.add('hidden');$('#startOverlay').classList.add('hidden')};$('#soundButton').onclick=()=>{sound=!sound;$('#soundButton').textContent=sound?'◖':'×'};loadMap(0);loop();
})();

